In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
#import xlrd
import openpyxl
from scipy.stats import multivariate_normal # used in gaussian pdf computation on mnist data.


#pip install openpyxl==3.0.5


In [2]:
data =pd.read_excel(r'C:/.../orgzn_data/orgzn_ratings.xlsx', engine='openpyxl') # import digits data

display(data)

exec_key_matrices_overall  Innovation_leader  Regulatory_leader  \
0                           8.0                5.0                5.0   
1                           7.0                NaN                NaN   
2                           5.0                NaN                NaN   
3                           NaN                NaN                NaN   
4                           NaN                NaN                NaN   
...                         ...                ...                ...   
7027                        7.0                7.0                8.0   
7028                        7.0                7.0                7.0   
7029                        7.0                7.0                8.0   
7030                        9.0                8.0                9.0   
7031                        8.0                8.0                9.0   

      Interoperability_leader  Network_and_Data_Security_leader  \
0                         5.0                               5.0   
1                         NaN                               NaN   
2                         NaN                               NaN   
3                         NaN                               NaN   
4                         NaN                               NaN   
...                       ...                               ...   
7027                      7.0                               9.0   
7028                      7.0                               7.0   
7029                      6.0                               7.0   
7030                      6.0                               8.0   
7031                      8.0                               9.0   

      Population_Health_leader  Rev_Cycle_Management_leader  PAS_leader  \
0                          5.0                          NaN         7.0   
1                          NaN                          NaN         NaN   
2                          NaN                          NaN         NaN   
3                          NaN                          NaN         NaN   
4                          NaN                          NaN         NaN   
...                        ...                          ...         ...   
7027                       NaN                          NaN         NaN   
7028                       3.0                          NaN         NaN   
7029                       7.0                          NaN         NaN   
7030                       8.0                          NaN         NaN   
7031                       8.0                          NaN         NaN   

      Business_intelligence_leader  
0                              NaN  
1                              NaN  
2                              NaN  
3                              NaN  
4                              NaN  
...                            ...  
7027                           NaN  
7028                           NaN  
7029                           NaN  
7030                           NaN  
7031                           NaN  

[7032 rows x 9 columns]

In [3]:
data.shape  # (7032, 9)

(7032, 9)

In [4]:
'Missing value treatment'

print("\nMissing Values % in Data:\n{}".format(data.isnull().sum(axis = 0)/data.shape[0]))

'remove NAs and drop columns with almost every observation as NA'
data_1 = data.dropna(axis=0, how='any', thresh=None, subset= data.columns[:-2], inplace=False).iloc[:, 0:-2]
print("\nShape of data:-\n",data_1.shape)
#PAS_leader and Business_intelligence_leader have lots of null values. Drop these two columns. 
#data_1 = data_1. # remove last two columns as they are completely NAs.


'percentage of null values after their treatment'

print("\nMissing Values % in Data_1:\n{}".format(data_1.isnull().sum(axis = 0)/data_1.shape[0]))


Missing Values % in Data:
exec_key_matrices_overall           0.086320
Innovation_leader                   0.352531
Regulatory_leader                   0.366752
Interoperability_leader             0.356940
Network_and_Data_Security_leader    0.380262
Population_Health_leader            0.468999
Rev_Cycle_Management_leader         0.564420
PAS_leader                          0.926479
Business_intelligence_leader        0.984642
dtype: float64

Shape of data:-
 (2656, 7)

Missing Values % in Data_1:
exec_key_matrices_overall           0.0
Innovation_leader                   0.0
Regulatory_leader                   0.0
Interoperability_leader             0.0
Network_and_Data_Security_leader    0.0
Population_Health_leader            0.0
Rev_Cycle_Management_leader         0.0
dtype: float64


In [5]:
'Transform features and response to array shape'

'''
There are ten rating categories on a scale of 1-10 in the response variable.Further to it, there are other six variables, 
namely, Innovation_leader, Regulatory_leader, Interoperability_leader, Network_and_Data_Security_leader,
Population_Health_leader,Rev_Cycle_Management_leader, PAS_leader, Business_intelligence_leader which contributes to overall
organization rating(exec_key_matrices_overall).

'''
#response var/dependent variable - this is overall rating 
dv= data_1['exec_key_matrices_overall'] 
dv_arr = np.array(dv)
print("\noverall ratings array (response variable):")
display(dv_arr)

#independent var
ivs = data_1.iloc[: , 1:]  # consider all columns except the dependent variabe(dv) as independent variable
features = ivs.iloc[:, :].values 
#features_arr = np.array(features) #Features Array
print("\nFeatures array:")
display(features)


overall ratings array (response variable):


array([7., 2., 7., ..., 4., 8., 8.])


Features array:


array([[7., 7., 7., 8., 7., 7.],
       [3., 6., 6., 7., 3., 5.],
       [7., 7., 7., 7., 7., 7.],
       ...,
       [5., 5., 5., 5., 5., 5.],
       [7., 9., 8., 8., 8., 7.],
       [9., 8., 8., 8., 8., 7.]])

In [6]:
'Distribution of rating labels[1-10] in dependent variable i.e. overall rating'

c = dict(sorted(dv.value_counts().to_dict().items())) 
#c= dict(sorted(c.items()))
print("\nlabel distribution in dependent variable:\n {}".format(c))


label distribution in dependent variable:
 {1.0: 31, 2.0: 27, 3.0: 133, 4.0: 82, 5.0: 202, 6.0: 261, 7.0: 1051, 8.0: 604, 9.0: 265}


In [7]:

"get the prior probability distribution from the data"
prior_prob = np.ones(len(c)) # 10 since we have 10 class labels in our data.
for i in range(len(c)):
    prior_prob[i] = c[i+1]/dv.shape[0] #dictionary start with 1 not with 0.
prior_prob
prior_prob_list = list(prior_prob)
print("\nPrior Probability Distribution of classes:\n{}".format(list(zip(c.keys(),prior_prob_list))))

"2- create function to form the gaussian distribution per class label"

'''
To define a gaussian distribution, we would need mean and variance parameters.Calculate mean and variance for
each class subset of data.
'''
def normdist(data):  
    var = np.cov(data.T)  # to compute covariance, we need to horizontally stack variables.
    mean_array = []
    for i in range(data.shape[1]):
        mu = np.mean(data[:,i])
        mean_array.append(mu)
    
    ma = np.array(mean_array) #mean array from subset of data having a particular class label.
    print("\nmean array-")
    display(ma)
    print("\nvariance matrix-")
    display(var)
    distribution = multivariate_normal(ma, var)
    return distribution


Prior Probability Distribution of classes:
[(1.0, 0.011671686746987951), (2.0, 0.01016566265060241), (3.0, 0.050075301204819275), (4.0, 0.030873493975903613), (5.0, 0.07605421686746988), (6.0, 0.09826807228915663), (7.0, 0.3957078313253012), (8.0, 0.22740963855421686), (9.0, 0.09977409638554217)]


In [8]:
'Obtain the probability distribution of observations across all class labels in the features data'

labels = list(c.keys())
predictedvalues_traindata = pd.DataFrame()
for i in range(9):
    X_class = np.array(features[dv == labels[i]]) 
    print("\nlabel flag for which to computer multivariate distribution: ",i+1)
    norm_dist=normdist(X_class)
    predictions_class = prior_prob_list[i]*norm_dist.pdf(features) 
    
    '''
    The probability of all of the observations in features array (which is having 2656 obs) belonging to the 
    class label=1 or any other class label is computed by prior probability of a particular class multiplied by
    norm_dist.pdf(features_arr) which renders a probability value for each observation in features data associated 
    with a particular class. 
    
    '''
    predictedvalues_traindata = pd.concat([predictedvalues_traindata, pd.DataFrame(predictions_class)], axis = 1)

print('Probability distribution of observations across all class labels in the data-')
predictedvalues_traindata.columns = ["1", "2", "3", "4", "5", "6", "7", "8", "9"] 
display(predictedvalues_traindata)


label flag for which to computer multivariate distribution:  1

mean array-


array([2.12903226, 2.4516129 , 2.38709677, 3.48387097, 3.03225806,
       1.83870968])


variance matrix-


array([[3.3827957 , 2.50645161, 1.91505376, 2.00215054, 2.12903226,
        0.72150538],
       [2.50645161, 3.45591398, 1.81935484, 2.67419355, 2.6516129 ,
        1.60860215],
       [1.91505376, 1.81935484, 3.11182796, 1.97311828, 2.02043011,
        1.16451613],
       [2.00215054, 2.67419355, 1.97311828, 4.72473118, 3.4172043 ,
        1.94731183],
       [2.12903226, 2.6516129 , 2.02043011, 3.4172043 , 3.5655914 ,
        1.50537634],
       [0.72150538, 1.60860215, 1.16451613, 1.94731183, 1.50537634,
        2.67311828]])


label flag for which to computer multivariate distribution:  2

mean array-


array([3.25925926, 4.18518519, 3.81481481, 5.59259259, 4.88888889,
       3.07407407])


variance matrix-


array([[4.04558405, 2.2962963 , 2.74216524, 1.87891738, 1.68376068,
        2.05698006],
       [2.2962963 , 4.38746439, 2.26638177, 0.5014245 , 2.82905983,
        1.56267806],
       [2.74216524, 2.26638177, 4.61823362, 1.07549858, 2.32478632,
        2.01424501],
       [1.87891738, 0.5014245 , 1.07549858, 4.48148148, 1.37606838,
        1.10826211],
       [1.68376068, 2.82905983, 2.32478632, 1.37606838, 4.94871795,
        1.73931624],
       [2.05698006, 1.56267806, 2.01424501, 1.10826211, 1.73931624,
        4.3019943 ]])


label flag for which to computer multivariate distribution:  3

mean array-


array([4.21052632, 4.54887218, 4.44360902, 5.60150376, 4.60902256,
       3.03007519])


variance matrix-


array([[2.47049442, 1.58054226, 1.42105263, 0.81180223, 0.8708134 ,
        0.38755981],
       [1.58054226, 3.06766917, 1.48951925, 1.18250171, 0.9965254 ,
        0.36215539],
       [1.42105263, 1.48951925, 3.1426293 , 1.30690362, 1.05354295,
        0.19110276],
       [0.81180223, 1.18250171, 1.30690362, 2.57484621, 0.69907724,
        0.09540898],
       [0.8708134 , 0.9965254 , 1.05354295, 0.69907724, 2.52779676,
        0.23154477],
       [0.38755981, 0.36215539, 0.19110276, 0.09540898, 0.23154477,
        2.78696742]])


label flag for which to computer multivariate distribution:  4

mean array-


array([5.15853659, 5.58536585, 4.85365854, 5.86585366, 5.13414634,
       3.73170732])


variance matrix-


array([[3.02393857, 1.39987955, 1.69015357, 0.73757904, 1.33649503,
        0.37639265],
       [1.39987955, 2.14694369, 1.67931346, 0.96838302, 1.04396266,
        0.54170431],
       [1.69015357, 1.67931346, 3.65733213, 0.72086721, 1.48900933,
        0.50346281],
       [0.73757904, 0.96838302, 0.72086721, 1.99412827, 0.58611864,
        0.02529359],
       [1.33649503, 1.04396266, 1.48900933, 0.58611864, 2.33980729,
        0.67841012],
       [0.37639265, 0.54170431, 0.50346281, 0.02529359, 0.67841012,
        3.30984643]])


label flag for which to computer multivariate distribution:  5

mean array-


array([5.31683168, 5.53960396, 5.25247525, 6.01485149, 5.31188119,
       4.1980198 ])


variance matrix-


array([[1.83941678, 0.77345944, 1.00916211, 0.52760948, 0.70168957,
        0.38471011],
       [0.77345944, 2.01086153, 0.88796118, 0.83274223, 0.75126841,
        0.61400916],
       [1.00916211, 0.88796118, 2.05036698, 0.62807251, 0.99051771,
        0.55672134],
       [0.52760948, 0.83274223, 0.62807251, 1.65649475, 0.50778287,
        0.50948229],
       [0.70168957, 0.75126841, 0.99051771, 0.50778287, 1.84751983,
        0.73892912],
       [0.38471011, 0.61400916, 0.55672134, 0.50948229, 0.73892912,
        2.44815526]])


label flag for which to computer multivariate distribution:  6

mean array-


array([5.87739464, 6.17241379, 5.77394636, 6.44827586, 5.76628352,
       4.89655172])


variance matrix-


array([[1.76183319, 0.91737401, 0.97217801, 0.55132626, 0.75969643,
        0.47188329],
       [0.91737401, 1.89708223, 0.91604775, 0.71087533, 0.73660477,
        0.65251989],
       [0.97217801, 0.91604775, 2.15254937, 0.37480106, 0.73542588,
        0.63806366],
       [0.55132626, 0.71087533, 0.37480106, 1.77135279, 0.40517241,
        0.2734748 ],
       [0.75969643, 0.73660477, 0.73542588, 0.40517241, 1.70285883,
        0.63342175],
       [0.47188329, 0.65251989, 0.63806366, 0.2734748 , 0.63342175,
        3.00848806]])


label flag for which to computer multivariate distribution:  7

mean array-


array([6.71741199, 6.94576594, 6.62416746, 7.07611798, 6.5394862 ,
       5.72312084])


variance matrix-


array([[1.66959177, 0.80370713, 0.95083594, 0.57581623, 0.83831181,
        0.57787323],
       [0.80370713, 1.78848444, 0.94721671, 0.73556069, 0.83309592,
        0.58782656],
       [0.95083594, 0.94721671, 1.81956776, 0.73625391, 0.86771148,
        0.61203117],
       [0.57581623, 0.73556069, 0.73625391, 1.44181958, 0.62365819,
        0.37919079],
       [0.83831181, 0.83309592, 0.86771148, 0.62365819, 1.8962965 ,
        0.82570522],
       [0.57787323, 0.58782656, 0.61203117, 0.37919079, 0.82570522,
        2.63278873]])


label flag for which to computer multivariate distribution:  8

mean array-


array([7.67880795, 7.76986755, 7.56788079, 7.77980132, 7.42549669,
       6.42880795])


variance matrix-


array([[1.13381218, 0.65730399, 0.70508934, 0.50295432, 0.56972862,
        0.54425994],
       [0.65730399, 1.27862618, 0.64168396, 0.57610677, 0.58730355,
        0.53002372],
       [0.70508934, 0.64168396, 1.32042602, 0.55311467, 0.64851515,
        0.58361339],
       [0.50295432, 0.57610677, 0.55311467, 1.18028785, 0.5863865 ,
        0.5174651 ],
       [0.56972862, 0.58730355, 0.64851515, 0.5863865 , 1.40240025,
        0.61491933],
       [0.54425994, 0.53002372, 0.58361339, 0.5174651 , 0.61491933,
        2.35810737]])


label flag for which to computer multivariate distribution:  9

mean array-


array([8.55471698, 8.49811321, 8.35849057, 8.49056604, 8.18113208,
       7.59245283])


variance matrix-


array([[0.67218411, 0.3855203 , 0.36856775, 0.25335906, 0.39535449,
        0.51859634],
       [0.3855203 , 0.94033734, 0.5025729 , 0.45168668, 0.5268582 ,
        0.65453116],
       [0.36856775, 0.5025729 , 0.88236135, 0.39922813, 0.43860778,
        0.43453402],
       [0.25335906, 0.45168668, 0.39922813, 0.6675243 , 0.31610921,
        0.47720126],
       [0.39535449, 0.5268582 , 0.43860778, 0.31610921, 1.3231275 ,
        0.91879646],
       [0.51859634, 0.65453116, 0.43453402, 0.47720126, 0.91879646,
        2.60600343]])

Probability distribution of observations across all class labels in the data-


1             2             3             4             5  \
0     5.108540e-09  1.116333e-07  1.849559e-07  7.128670e-07  6.659887e-06   
1     1.090230e-10  4.953294e-09  3.148156e-07  2.187107e-07  1.902905e-07   
2     3.168571e-09  1.213308e-07  2.449083e-07  1.506575e-06  9.507850e-06   
3     6.974245e-11  1.208478e-08  4.035059e-09  9.583467e-08  1.646815e-07   
4     1.331059e-10  1.909961e-08  2.928436e-07  1.776657e-07  2.582055e-07   
...            ...           ...           ...           ...           ...   
2651  6.338815e-08  1.323396e-07  1.289208e-06  9.606569e-08  8.164453e-07   
2652  3.026559e-12  2.233470e-09  9.353191e-10  1.718575e-08  2.057358e-08   
2653  3.490336e-07  5.535480e-07  7.266873e-06  8.509856e-06  4.383230e-05   
2654  1.295224e-09  3.122057e-08  3.296048e-08  2.284518e-07  1.268605e-06   
2655  1.702395e-10  1.892939e-08  1.381002e-08  2.183818e-07  6.299300e-07   

                 6             7             8             9  
0     2.128361e-05  3.079790e-04  3.871708e-04  7.697831e-05  
1     2.450514e-07  3.309587e-07  1.210784e-10  7.528153e-16  
2     3.232948e-05  4.006970e-04  4.293128e-04  5.375391e-05  
3     9.558212e-07  4.680479e-05  1.612992e-04  2.063840e-04  
4     1.055208e-07  1.668037e-07  1.195353e-10  3.602941e-18  
...            ...           ...           ...           ...  
2651  4.455722e-07  5.906738e-07  4.481004e-08  1.057606e-11  
2652  3.268852e-07  1.558158e-06  6.205806e-07  6.543586e-08  
2653  4.174862e-05  8.487271e-05  5.319942e-06  5.905765e-10  
2654  4.238462e-06  1.094390e-04  1.241001e-04  2.952967e-05  
2655  3.287164e-06  1.125088e-04  3.019539e-04  4.342959e-04  

[2656 rows x 9 columns]

In [9]:
#use features_arr of test data to predict probs on test features

In [10]:
'get the maximum probability for each observation to belong to a particular class'

'''
retrieve the maximum value out from each row/observation and check its respective class label(column) to get the overall
rating 
'''
# assign column names = class labels in our data
predictedvalues_traindata = predictedvalues_traindata.idxmax(axis=1, skipna=True) # get the max value in row and column name corresponding to that maximum rowvalue.


predictedvalues_traindata1 = list(predictedvalues_traindata)
predictedvalues_traindata1 = [int(i) for i in predictedvalues_traindata1]
temp= pd.DataFrame(list(zip(list(predictedvalues_traindata1), list(dv))), columns =['predicted_rating', 'actual_overallrating'])
print("Actual overall ratings and Predicted Ratings-")
display(temp)


#temp['indexval'] = ind

corr_data= round(float(temp.corr(method ='pearson').iloc[1][[0]]),2)
print("Correlation between actual rating and predicted ratings: ",corr_data)


print("\ncorrelation between actual and predictions-")
pd.crosstab(temp['actual_overallrating'], temp['predicted_rating'], rownames=['actual_overallrating'], colnames=['predicted_rating'])


Actual overall ratings and Predicted Ratings-


predicted_rating  actual_overallrating
0                    8                   7.0
1                    7                   2.0
2                    8                   7.0
3                    9                   9.0
4                    3                   3.0
...                ...                   ...
2651                 3                   3.0
2652                 7                   7.0
2653                 7                   4.0
2654                 8                   8.0
2655                 9                   8.0

[2656 rows x 2 columns]

Correlation between actual rating and predicted ratings:  0.68

correlation between actual and predictions-


predicted_rating       1   2   3   4   5   6    7    8    9
actual_overallrating                                       
1.0                   17   1   9   0   3   0    0    1    0
2.0                    0  10  10   1   1   0    3    2    0
3.0                    3   5  59   3  29   4   27    3    0
4.0                    1   0  16  10  16   5   32    2    0
5.0                    0   3  26   1  33   9  118   12    0
6.0                    0   3  12   5  22  18  181   18    2
7.0                    0   8  23  10  26  18  623  286   57
8.0                    0   2   4   1   6  10  192  250  139
9.0                    0   0   2   0   0   0   44   51  168

In [ ]:
'''
We observe that the matrix is dense diagonally which implies that most of our actual and predicted rating re similar.
'''

In [11]:
#https://peterroelants.github.io/posts/multivariate-normal-primer/